title: Mathies G. Aarhus
url: "https://mathiesaarhus.github.io/"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "publications"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
   name: "Code"
   link: https://github.com/mathiesaarhus/
 - name: "About"
   link: "/researcher/"
