title: Mathies Aarhus
url: "https://mathiesaarhus.github.io/"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer:
  - name: "Twitter"
    link: "https://twitter.com/aarhus_g"
    icon: "fab fa-twitter"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/mathies-aarhus-0137209b/"
    icon: "fab fa-linkedin-in"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "/https://portal.findresearcher.sdu.dk/en/persons/mathies/publications//" 
 - name: "CV"
   link: "CV.pdf"
 - name: "Code"
   link: "https://mathiesaarhus.github.io/"
 - name: "Contact"
   link: "mailto:mathies@sdu.dk" 
